edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
fn_params_layout = "Tall"
reorder_imports = true
reorder_modules = true
match_block_trailing_comma = false
remove_nested_parens = true
short_array_element_width_threshold = 10
