[package]
name = "pellucid-relay-bin"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "stream relay binary"

[lints]
workspace = true

[[bin]]
name = "pellucid-relay-bin"
path = "src/main.rs"

[dependencies]
