/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.
 *
 * To regenerate, run `bunx convex codegen`.
 * @module
 */

import { anyApi } from "convex/server";

export const api = anyApi;
export const internal = anyApi;
